##
# Ansible playbook for setting up logstash shipper on an existing server
#
---
##
# Create necessary folders to ship logs to logstash.
#

- name: Create folders
  file: path={{ item }}/logstash owner=root group=root mode=0645 state=directory
  with_items:
    - /etc
    - /opt
    - /var/log

- name: Unarchive logstash
  unarchive: src=/root/logstash-1.4.2.tar.gz dest=/opt/logstash

- name: Add shipper.conf
  template: src=shipper-conf.j2 dest=/etc/logstash/shipper.conf owner=root group=root mode=0645

- name: Add logstash-shipper init file
  template: src=logstash-shipper-init.j2 dest=/etc/init.d/logstash-shipper owner=root group=root mode=645

- name: Enable logstash-shipper init
  command: update-rc.d logstash-shipper defaults

# - name: Get FQDN of server
#   command: hostname -f
#   register: fqdn

# - name: Update logs to use FQDN for logstash
#   lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' insertbefore="localhost" line="{{ fqdn }} " owner=root group=root mode=0644

- name: Start logstash-shipper
  service: name=logstash-shipper state=started

