##
# Ansible playbook for setting up logstash shipper on an existing server
#
---
##
# Use the logstash-forwarder library to manage shipping logs
##
- name: Add GPG key for logstash forwarder
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Create cert directory
  file: path=/etc/pki/tls/certs state=directory

- name: Copy cert for forwarder into place
  template: src=logstash-forwarder-crt.j2 dest=/etc/pki/tls/certs/logstash-forwarder.crt

- name: Add forwarder pkg to sources
  apt_repository: repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main' state=present update_cache=yes

- name: Install logstash forwarder
  apt: name=logstash-forwarder

- name: Add logstash forwarder init script
  template: src=logstash-forwarder-init.j2 dest=/etc/init.d/logstash-forwarder mode="0775"

- name: Update rc.d
  command: update-rc.d logstash-forwarder defaults

- name: Add logstash forwarder config file
  template: src=logstash-forwarder-config.j2 dest=/etc/logstash-forwarder

- name: Restart forwarder
  service: state=restarted name=logstash-forwarder
