---
- name: add some hosts
  hosts: localhost
  vars_files:
  - roles/mongo/vars/mongo-settings.yml

  tasks:
    - add_host:
        name: "{{ item }}"
        ansible_ssh_host: 127.0.0.1
        groups: os_api
        ansible_connection: local
        oshost: "{{ item }}"
      with_items: servers
    - debug: var=groups

- name: Spin up new servers
  hosts: os_api
  user: root
  serial: 1

  vars_files:
    - roles/mongo/vars/mongo-settings.yml
  roles:
    - nova

- name: Add mongo to new servers
  hosts: mongo
  user: root

  roles:
    - mongo
