---

- name: Update software packages
  hosts: all
  sudo: True
  tasks:
    - name: update apt
      apt: update_cache=yes cache_valid_time=3600

- name: Setup web services
  hosts: all
  sudo: True

  vars_files:
    - roles/webserver/vars/webserver-settings.yml

  roles:
    - { role: webserver, tags: [ 'lamp' ] }
