##
# Ansible playbook for spinning up and deploying a new Varnish server.
#
---
- name: add some hosts
  hosts: localhost
  vars_files:
    - roles/varnish/vars/varnish-settings.yml

  tasks:
    - add_host:
        name: "{{ item }}"
        ansible_ssh_host: 127.0.0.1
        groups: os_api
        ansible_connection: local
        oshost: "{{ item }}"
      with_items: servers
    - debug: var=groups

- name: Spin up new servers
  hosts: os_api
  user: root
  serial: 1

  vars_files:
    - roles/varnish/vars/varnish-settings.yml
  roles:
    - nova

- name: Add varnish to new servers
  hosts: varnish
  user: ubuntu
  sudo: yes
  vars_files:
    - roles/varnish/vars/varnish-settings.yml

  roles:
    - common-tasks
    - varnish

