##
# Ansible playbook for setting up a LAMP development server on Ubuntu 14.04.
#
---
- name: add some hosts
  hosts: localhost
  
  roles: 
    - add_host

- name: Spin up new servers
  hosts: os_api
  user: root
  sudo: yes

  serial: 1

  vars_files:
    - roles/webserver/vars/webserver-settings.yml
    - roles/common-tasks/vars/common-secret.yml

  roles:
    - nova

- name: Setup the new webservers
  hosts: newly-created
  user: ubuntu
  sudo: yes
  vars_files:
    - roles/webserver/vars/webserver-settings.yml
    - roles/common-tasks/vars/common-secret.yml

  roles:
    - common-tasks
    - role: leonidas.nvm
      nvm:
        user: dosomething
        version: v0.17.0
        node_version: '0.10'
    - webserver

