##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
- hosts: webserver
  user: root

  vars_files:
    - roles/webserver/vars/webserver-settings.yml

  roles:
    - nova
    - webserver