# Settings that are applied to new Mongo servers spun up in OpenStack.

---
servers:
  - mongo3

flavor: ds.4gb-80gb

type: mongo

tenant: beta.dosomething.org

security_groups: default,mongodb

tier: production

replSet: activity

