# Settings that are applied to new Mongo servers spun up in OpenStack.

---
servers:
  - mongo1
  - mongo2

flavor: ds.4gb-80gb

type: mongo

tenant: beta.dosomething.org

groups:
  - default
  - varnish

environment: production
tier: production

