##
# Ansible playbook for setting up new servers in openstack
#
---
- name: Create new server in OpenStack
  hosts: localhost

  tasks:
    - name: create instances
      nova_compute:
        state: present
        name: {{ item }}
        with_items: servers
        auth_url: "{{ ansible_env.OS_AUTH_URL }}"
        flavor_id: {{ flavor }}
        image_id: cb976ddc-c7e6-493d-85a6-d3364d3e411d
        key_name: search
        login_username: "{{ ansible_env.OS_USERNAME }}"
        login_password: "{{ ansible_env.OS_PASSWORD }}"
        login_tenant_name: {{ tenant }}
        security_groups: {{ item }}
        with_items: groups
        wait_for: 500
        meta:
          type: {{ type }}
      register: nova

    - name: Display what we get back from nova
      debug: var=nova

    - name: add instance with ssh ip
      add_host: name={{ nova.info.name }}
                ansible_ssh_host={{ item }}
                ansible_ssh_private_key_file=~/.ssh/search.pem
                groups={{ nova.metadata.info.type }}
      with_items: nova.private_ip

    - name: wait for instance to boot
      wait_for:
        host: "{{ item }}"
        port: 22
      with_items: nova.private_ip

    ##
    # Create dosomething user.
    #
    - include: ../common-tasks/dosomething-user.yml

