##
# Ansible playbook for setting up new servers in openstack
#
---
- name: create openstack stuff
  hosts: localhost

  tasks:
    - name: create instances
      nova_compute:
        state: present
        name: varnish2
        auth_url: "{{ ansible_env.OS_AUTH_URL }}"
        flavor_id: ds.4gb-30gb
        image_id: cb976ddc-c7e6-493d-85a6-d3364d3e411d
        key_name: search
        login_username: "{{ ansible_env.OS_USERNAME }}"
        login_password: "{{ ansible_env.OS_PASSWORD }}"
        login_tenant_name: "{{ ansible_env.OS_TENANT_NAME }}"
        security_groups: default
        wait_for: 500
        meta:
          type: coreos
      register: nova

    - name: Display what we get back from nova
      debug: var=nova

# - name: add instance with ssh ip
#   add_host: hostname={{ inventory_hostname }}_real ansible_ssh_host={{ item }} groups={{ group_names[0] }}_real
#   with_items: nova.private_ip

# - name: wait for instance to boot
#   wait_for:
#     host: "{{ item }}"
#     port: 22
#   with_items: nova.private_ip