##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#
---
- name: General | Install required packages.
  apt: name={{ item }} state=latest
  tags: common
  with_items:
    - tomcat7
    - tomcat7-admin
