---
- name: General | Install required packages.
  apt: name={{ item }} state=latest
  tags: lamp
  with_items:
    - php5
    - php5-mysql
    - php5-curl
    - php5-fpm
    - php5-cli
    - php5-cgi
    - php5-dev
    - php-pear
    - php5-gd
    - php-apc
    - php5-gd
    - php-soap
    - php5-xmlrpc
    - php5-mcrypt
    - nginx
    - mysql-server
    - mysql-client
    - sendmail
    - unzip
    - python-mysqldb
    - glusterfs-client
    - python-zmq
    - libpcre3-dev

##
# PHP Setup.
#
- name: Composer | Install PHP Composer
  action: shell curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
  tags: lamp

##
# MySQL database setup.
#
- name: MySQL | Configuration file, my.cnf
  action: template src=etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
  tags: lamp

- include: ./mysql-secure.yml

##
# NGiNX setup
#
- name: NGiNX | Configuration file for our site
  action: template src=etc-nginx-sites-available-dosomething.j2 dest=/etc/nginx/sites-available/default
  tags: lamp

# Create docroot
- name: Creates directory
  file: path=/var/www/beta.dosomething.org state=directory  group=dosomething owner=dosomething

##
# FTP server setup.
#
- name: FTP | vsftpd daemon package
  action: apt pkg=vsftpd state=installed
  tags: ftp

- name: FTP | Configuration setup
  action: template src=etc-vsftpd-conf.j2 dest=/etc/vsftpd.conf
  tags: ftp

##
# Drush install, a Drupal shell tool.
#
- include: ./ubuntu-drush.yml

#- npm: name=bower global=yes
#- npm: name=grunt-cli global=yes

##
# Redis server.
#
- name: Redis | Install redis
  action: apt pkg=redis-server state=installed
  tags: redis

##
# Restart services
#
- name: Restart NGiNX
  action: service name=nginx state=restarted
  tags: lamp

- name: Restart MySQL
  action: service name=mysql state=restarted
  tags: lamp

- name: Restart vsftpd
  action: service name=vsftpd state=restarted
  tags: ftp

