##
# Ansible playbook for setting up a LAMP development server on Ubuntu 10.04.
#

---
- hosts: all
  user: root

  vars_files:
    - settings.yml

  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: General | Install required packages.
      action: apt pkg=$item state=installed
      tags: common
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - sendmail
        - unzip
        - python-mysqldb

    ##
    # Message of the day explaining server is under Ansible control.
    #
    - name: General | Message of the day explaining server is under Ansible control.
      action: copy src=files/etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755
      tags: common

    ##
    # PHP Setup.
    #
    - name: PHP | Configuration file, php.ini
      action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
      tags: common

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file, my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common

    - include: ../common-tasks/mysql-secure.yml

    ##
    # Apache2 setup. Webroot is at /var/dev, rather than /var/www because
    # strictly speaking /var/www is owned by an apt package.
    #
    - name: Apache | Enable some required modules
      action: command a2enmod rewrite vhost_alias
      tags: common

    - name: Apache | Configuration file for our site
      action: template src=templates/etc-apache2-sites-available-devserver.j2 dest=/etc/apache2/sites-available/devserver
      tags: common

    - name: Apache | Disable the default site
      action: command a2dissite default
      tags: common

    - name: Apache | Enable our new site
      action: command a2ensite devserver
      tags: common

    ##
    # Drush install, a Drupal shell tool.
    #
    - include: ../common-tasks/ubuntu-drush.yml

    ##
    # eAccelerator opcode cache.
    #
    - include: ../common-tasks/ubuntu-eaccelerator.yml

    ##
    # Memcached daemon.
    - include: ../common-tasks/ubuntu-memcached.yml

    ##
    # Restart services
    #
    - name: Restart Apache
      action: service name=apache2 state=restarted
      tags: common

    - name: Restart MySQL
      action: service name=mysql state=restarted
      tags: common

    - name: Restart Memcached
      action: service name=memcached state=restarted
      tags: memcached
