##
# Ansible playbook for setting up new servers in openstack.
# Variables for creating instances should be defined by the
# role calling these tasks.  Environment vars should be defined
# in the controller node.
#
---
- name: Create Instances
  nova_compute:
    state: present
    name: "{{ inventory_hostname }}"
    auth_url: "{{ ansible_env.OS_AUTH_URL }}"
    flavor_id: "{{ flavor }}"
    image_id: "{{ image_id }}"
    key_name: "{{ ansible_env.OS_KEY_NAME }}"
    login_username: "{{ ansible_env.OS_USERNAME }}"
    login_password: "{{ ansible_env.OS_PASSWORD }}"
    login_tenant_name: "{{ ansible_env.OS_TENANT_NAME }}"
    security_groups: "{{ security_groups }}"
    wait_for: 60
    meta:
      type: "{{ type }}"
      tier: "{{ tier }}"
  register: nova
  tags: nova

- name: Display what we get back from nova
  debug: var=nova.info.name

- name: add instance with ssh ip
  add_host:
    name: "{{ nova.info.name }}.{{ nova.info.id }}"
    ansible_ssh_host: "{{ nova.private_ip }}"
    ansible_ssh_private_key_file: ~/.ssh/search.pem
    groups: "newly-created"

- name: wait for instance to boot
  wait_for:
    host: "{{ item }}"
    port: 22
  with_items: nova.private_ip
  tags: nova



